name: Deps

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - deps/**

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install python3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      with:
        version: "2020.8.13" # yamllint disable-line rule:quoted-strings

    - name: Configure git user
      run: |
        git config --global user.email '72795724+arhatbot@users.noreply.github.com'
        git config --global user.name 'Arhat Bot'

    - name: Update lockfile
      run: |
        make lock

    - name: Push lockfile
      run: |
        git add --all .
        if git commit -m 'deps(lock): Update packages lock'; then
          git push
        else
          echo "no package checksum changed, skipping push"
        fi
