name: Deps

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - deps/**

jobs:
  vendor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install python3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Configure git user
      run: |
        git config --global user.email '72795724+arhatbot@users.noreply.github.com'
        git config --global user.name 'Arhat Bot'

    - name: Update lockfile
      run: |
        make lock

    - name: Push vendored packages
      run: |
        git add --all .
        if git commit -m 'deps(vendor): Update vendored packages'; then
          git push
        else
          echo "no vendored package changed, skipping push"
        fi
